version: '3.8'

services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: gin-sample
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
    driver: local
